[package]
name = "rust-crud-app"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
axum = "0.7.9"
serde_json = "1.0.133"
serde = { version = "1.0.215", features = ["derive"] }
